=== DmitriyDunaev/Obfuscation/ObfuscationManager/Schemas/Exchange.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 sp1 (http://www.altova.com) by End User (free.org) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Routine">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Global" type="Variables" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="Function" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="Description" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Function">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Local" type="Variables" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="BasicBlock" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="ID" type="myID" use="required"/>
			<xs:attribute name="GlobalID" type="xs:string" use="required"/>
			<xs:attribute name="CalledFrom" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="InternalOnly"/>
						<xs:enumeration value="ExternalOnly"/>
						<xs:enumeration value="Both"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="RefInputVars" type="myIDREFS" use="optional"/>
			<xs:attribute name="RefOutputVars" type="myIDREFS" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="BasicBlock">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Instruction" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="ID" type="myID" use="required"/>
			<xs:attribute name="Predecessors" type="myIDREFS" use="optional"/>
			<xs:attribute name="Successors" type="myIDREFS" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Instruction">
		<!--TAC instruction is given in the innerText-->
		<xs:complexType mixed="true">
			<xs:attribute name="ID" type="myID" use="required"/>
			<xs:attribute name="StatementType" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="FullAssignment"/>
						<xs:enumeration value="UnaryAssignment"/>
						<xs:enumeration value="Copy"/>
						<xs:enumeration value="UnconditionalJump"/>
						<xs:enumeration value="ConditionalJump"/>
						<xs:enumeration value="Procedural"/>
						<xs:enumeration value="IndexedAssignment"/>
						<xs:enumeration value="PointerAssignment"/>
						<xs:enumeration value="NoOperation"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="PolyRequired" type="xs:boolean" use="optional" default="false"/>
			<xs:attribute name="RefVars" type="myIDREFS" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Variable">
		<!--Variable's name is given in the innerText-->
		<xs:complexType mixed="true">
			<xs:simpleContent>
				<xs:extension base="myVariable">
					<xs:attribute name="ID" type="myID" use="required"/>
					<xs:attribute name="Pointer" type="xs:boolean" use="required"/>
					<xs:attribute name="MemoryRegionSize" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:integer">
								<xs:minExclusive value="0"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="MemoryUnitSize" use="optional">
						<xs:simpleType>
							<xs:restriction base="xs:integer">
								<xs:minExclusive value="0"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="FixedValue" type="xs:string" use="optional"/>
					<xs:attribute name="MinValue" type="xs:integer" use="optional"/>
					<xs:attribute name="MaxValue" type="xs:integer" use="optional"/>
					<xs:attribute name="GlobalID" type="xs:string" use="optional"/>
					<xs:attribute name="Fake" type="xs:boolean" use="optional"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="myID">
		<xs:restriction base="xs:ID">
			<xs:pattern value="ID_[A-F0-9]{8}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{12}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="myIDREFS">
		<xs:restriction base="xs:IDREFS">
			<xs:pattern value="(ID_[A-F0-9]{8}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{12} ){1,}ID_[A-F0-9]{8}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{12}|ID_[A-F0-9]{8}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{12}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="myVariable">
		<xs:restriction base="xs:string">
			<xs:pattern value="[vtcfd]_ID_[A-F0-9]{8}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{12}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="Variables">
		<xs:sequence>
			<xs:element ref="Variable" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== DmitriyDunaev/Obfuscation/ObfuscationManager/Schemas/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2011 sp1 (http://www.altova.com)-->
<Routine Description="test routine" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Exchange.xsd">
	<Function CalledFrom="ExternalOnly" ID="ID_1" ExternalLabel="sub_401334">
		<Outputs>
			<Original>
				<Variable ID="ID_200" Size="dword" Pointer="false">t_0</Variable>
			</Original>
		</Outputs>
		<Locals>
			<Original>
				<Variable ID="ID_220" Size="dword" Pointer="false" ConstValueInParam="0">0</Variable>
				<Variable ID="ID_221" Size="dword" Pointer="false" ConstValueInParam="1">1</Variable>
			</Original>
		</Locals>
		<BasicBlock ID="ID_3" Successors="ID_4 ID_7">
			<Instruction ID="ID_101" StatementType="Call">sub_401980()</Instruction>
			<Instruction ID="ID_102" StatementType="Call" RefVars="ID_200 ID_220 ID_221">t_0 = sub_401368(0, 1)</Instruction>
		</BasicBlock>
		<BasicBlock ID="ID_4" Predecessors="ID_3">
			<Instruction ID="ID_120" StatementType="UnconditionalJump" RefVars="ID_200">return t_0</Instruction>
		</BasicBlock>
	</Function>
	<Function CalledFrom="InternalOnly" ID="ID_2" ExternalLabel="">
		<Inputs>
			<Original>
				<Variable ID="ID_201" Size="dword" Pointer="false">a1</Variable>
				<Variable ID="ID_202" Size="dword" Pointer="false">a2</Variable>
			</Original>
		</Inputs>
		<Outputs>
			<Original>
				<Variable ID="ID_205" Size="byte" Pointer="true">v5</Variable>
			</Original>
		</Outputs>
		<Locals>
			<Original>
				<Variable ID="ID_203" Size="byte" Pointer="false">v3</Variable>
				<Variable ID="ID_204" Size="dword" Pointer="false">v4</Variable>
				<Variable ID="ID_206" Size="dword" Pointer="false">i</Variable>
				<Variable ID="ID_207" Size="dword" Pointer="true">v7</Variable>
				<Variable ID="ID_208" Size="byte" Pointer="true">v8</Variable>
				<Variable ID="ID_209" Size="dword" Pointer="false">v9</Variable>
				<Variable ID="ID_210" Size="dword" Pointer="false">t_0</Variable>
				<Variable ID="ID_211" Size="dword" Pointer="false">t_1</Variable>
				<Variable ID="ID_212" Size="dword" Pointer="false" ConstValueInParam="3">3</Variable>
				<Variable ID="ID_213" Size="dword" Pointer="false" ConstValueInParam="0">0</Variable>
				<Variable ID="ID_214" Size="dword" Pointer="false" ConstValueInParam="4">4</Variable>
				<Variable ID="ID_215" Size="dword" Pointer="false" ConstValueInParam="1">1</Variable>
			</Original>
		</Locals>
		<BasicBlock ID="ID_7" Predecessors="ID_3" Successors="ID_9">
			<Instruction ID="ID_103" StatementType="FullAssignment" RefVars="ID_210 ID_212 ID_202">t_0 := 3 * a2 </Instruction>
			<Instruction ID="ID_104" StatementType="FullAssignment" RefVars="ID_211 ID_210 ID_201">t_1 := t_0 + a1 </Instruction>
			<Instruction ID="ID_105" StatementType="Copy" RefVars="ID_209 ID_211">v9 := t_1</Instruction>
			<Instruction ID="ID_106" StatementType="PointerAssignment" RefVars="ID_208 ID_203">v8 := &amp;v3</Instruction>
			<Instruction ID="ID_107" StatementType="PointerAssignment" RefVars="ID_205 ID_203">v5 := &amp;v3</Instruction>
			<Instruction ID="ID_108" StatementType="PointerAssignment" RefVars="ID_207 ID_204">v7 := &amp;v4</Instruction>
			<Instruction ID="ID_109" StatementType="Copy" RefVars="ID_206 ID_213">i := 0</Instruction>
		</BasicBlock>
		<BasicBlock ID="ID_9" Predecessors="ID_7 ID_13" Successors="ID_13 ID_10">
			<Instruction ID="ID_110" StatementType="ConditionalJump" RefVars="ID_206 ID_214 ID_112">if i &lt;= 4 goto ID_112 </Instruction>
		</BasicBlock>
		<BasicBlock ID="ID_10" Predecessors="ID_9" Successors="ID_16">
			<Instruction ID="ID_111" StatementType="UnconditionalJump" RefVars="ID_119">goto ID_119</Instruction>
		</BasicBlock>
		<BasicBlock ID="ID_13" Predecessors="ID_9" Successors="ID_9">
			<Instruction ID="ID_112" StatementType="FullAssignment" RefVars="ID_202 ID_206">a2 := i + a2</Instruction>
			<Instruction ID="ID_113" StatementType="Copy" RefVars="ID_208 ID_209">v8 := v9</Instruction>
			<Instruction ID="ID_114" StatementType="PointerAssignment" RefVars="ID_207 ID_202">*v7 := a2</Instruction>
			<Instruction ID="ID_115" StatementType="FullAssignment" RefVars="ID_208 ID_214">v8 := 4 + v8</Instruction>
			<Instruction ID="ID_116" StatementType="FullAssignment" RefVars="ID_207 ID_215">v7 := 1 + v7</Instruction>
			<Instruction ID="ID_117" StatementType="FullAssignment" RefVars="ID_206 ID_215">i := 1 + i</Instruction>
			<Instruction ID="ID_118" StatementType="UnconditionalJump" RefVars="ID_110">goto ID_110</Instruction>
		</BasicBlock>
		<BasicBlock ID="ID_16" Predecessors="ID_10" Successors="ID_3">
			<Instruction ID="ID_119" StatementType="UnconditionalJump" RefVars="ID_205">return v5</Instruction>
		</BasicBlock>
	</Function>
</Routine>
